### ISSUE TITLE
URI's being treated as labels

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#5] opened 2020-09-21 21:37 UTC
Somehow a couple of URI's are being mistaken for labels.
Currently, our output is inconsistent and looks like this:
_bf:expressionOf <https://trellis.sinopia.io/repository/washington/b7ef5c30-4e4c-459c-8361-2c371359894f>_; or
_bf:expressionOf [ a bf:Work ;
            rdfs:label "https://trellis.sinopia.io/repository/washington/0a4ea663-988e-474b-a25e-659b935b65a9" ],
        [ a bf:Work.subclass ;
            rdfs:label "https://trellis.sinopia.io/repository/washington/0a4ea663-988e-474b-a25e-659b935b65a9" ] ;_
[bf:relatedTo](https://id.loc.gov/ontologies/bibframe.html#p_relatedTo) has the same issue with URIs being listed as labels. I'm not sure whether we need to fix this or if it's a Sinopia issue.

**Comment by CECSpecialistI** [comment] 2020-09-22 19:51
@briesenberg07 Crud, for the properties also in our sinopia application profiles in AdminMetadata, we're outputting bad BIBFRAME. We only did it correctly for bf:status. We need to fix these. I don't know where our profiles are living right now or where the AdminMetadata profile is, but if you point me in the right direction I can fix this problem and future source data won't look this way (at least for the data that starts out as BIBFRAME).

**Comment by briesenberg07** [comment] 2020-09-23 03:56
@CECSpecialistI I believe that the place to fix it, if you wanted to fix it at this point, would be in the [source profile](https://github.com/uwlib-cams/UWLibCatProfiles/blob/master/WAU.profile.RDA.json), as this is processed to output the [AdminMetadata profile](https://github.com/uwlib-cams/UWLibCatProfiles/blob/master/WAU.profile.RDA.adminMetadata.json) that is actually loaded into Sinopia.

**BUT WAIT!** *No, none of this applies anymore!* There is no more loading JSON profiles to Sinopia! There are no more profiles in Sinopia, period--only resource templates!

I'd think that your best bet would be to wait until the UW RTs have been converted to the new RDF format on [production](https://sinopia.io/) and then edit them there (in the Linked-Data Editor itself, which will now be the graphical editing interface for RTs).

More long-term, I hope to output new Sinopia RDF RTs from an updated source. So we would want to make sure that the proper structure was input for BIBFRAME adminMetadata/AdminMetadata/etc. in this new source.

**Comment by CECSpecialistI** [comment] 2020-09-23 15:22
That makes sense. We still have a problem with the properties outside of AdminMetadata, but we can wait on the AdminMetadata properties until we can edit the input forms themselves (unless it's super easy to fix the data! because if it is, and we're adding this data to sinopia, we should probably clean the data in addition to fixing the original problem with the resource templates)?

**Comment by briesenberg07** [comment] 2020-09-23 15:47
>(unless it's super easy to fix the data! because if it is, and we're adding this data to sinopia, we should probably clean the data in addition to fixing the original problem with the resource templates)?

I don't think we've seriously considered cleaning our RDA/RDF. We've considered it as experimental data, and going forward it may be considered as "legacy data." If we were close to loading converted BF into the Sinopia backend, perhaps this would change and we would consider some data cleanup? But I don't think it would be super easy.

As has been discussed, there are a few things between now and loading converted BF into Sinopia:
* Further refinement of RML conversion
* Alignment of output BF with stable Sinopia RTs
* Establishment of a workflow for loading triples into mongoDB en masse

With new resource templates for creating RDA/RDF in Sinopia, the data created with these will benefit from all of the above steps, could begin flowing back into Sinopia, and might be considered as something more than experimental...

**Comment by briesenberg07** [comment] 2020-09-23 23:05
>bf:descriptionLanguage and bf:source values should be bnodes with values of bf:Language and bf:Source, like this:

@CECSpecialistI I don't understand what you're saying that AdminMetadata output should look like based on your snippet above. Seems like it got a little garbled somehow, maybe from copy/paste? Is it supposed to be RDF/XML?

Also, I don't understand how the value for bf:descriptionLanguage would be a bnode since given the snippet 
```
bf:descriptionLanguage
<bf:Language rdf:about="http://id.loc.gov/vocabulary/languages/eng">
bf:codeeng</bf:code>
</bf:Language>
</bf:descriptionLanguage>
```
I may be reading this incorrectly, but my best interpretation is that this is RDF/XML making two statements on a given IRI, http://id.loc.gov/vocabulary/languages/eng:
* It has rdf:type bf:Language
* It has bf:code value "eng" (looks like maybe some copy/paste garbling here)

Please clarify what you think the output should look like--thank you!

**Comment by gerontakos** [comment] 2020-09-24 00:44
<instanceOfBf:AdminMetadata> bf:descriptionLanguage <https://id.loc.gov/vocabulary/languages/eng>

--or, in RDF/XML:

<rdf:Description rdf:node="AdminMetadataNode">
    <bf:descriptionLanguage rdf:resource="https://id.loc.gov/vocabulary/languages/eng"/>

...is correct. No type bf:Language is needed due to direct IRI entry.

Does that make sense?

So I think this is not a problem issue.

However if IRIs are being output as literals (as in the expressionOf example) that leads to problems, as we have one way of processing the RDA input if the value is a literal and another if the value is an IRI. I suspect the problem is in the input RDA data. We'll need to look at that. I'll be on the watch for that. All triples I've seen with <http://expression-as-bf-Work> bf:expressionOf <http://rdaWork-as-bf-Work> have had IRI values as the triple's object.

**Comment by CECSpecialistI** [comment] 2020-09-28 15:51
ack you guys are right about language

**Comment by CECSpecialistI** [comment] 2020-09-28 16:00
Updated the issue to only include the one thing we need to watch.

**Comment by mcm104** [comment] 2020-09-30 22:56
I wrote up a simple script ([fix_URIs.py](https://github.com/uwlib-cams/rml/blob/master/fix_URIs.py)) that can fix URIs that have been entered as literals by mistake! It basically just goes through the RDFXML looking for this:
`<`_(property)_`>`_(literal beginning with "http")_`</`_(property)_`>`

and replaces it with this:
`<`_(property)_` rdf:resource=`_(that same literal now as a URI)_`/>`

With that all fixed, the output BF will be fixed, too.

The only issue: are there any instances in our data where a URI is _supposed_ to be a literal? If not, this script is good to go, but if so, I'll need to make some exceptions.

**Comment by briesenberg07** [comment] 2020-10-01 16:59
Need to take a closer look at this...
I knew that Sinopia was generating URI labels for URIs
```
<> <property> <uriValue01>
[...]
<uriValue01> <rdfs:label> "http://uriValue01.com"
```
But I wasn't aware that the URIs-as-literals were actually ending up in the object position, like...
```
<> <property> "http://uriValue01.com"
```

**Comment by mcm104** [comment] 2020-10-19 23:04
Issue is with original RDA, not with RML mapping. Currently resolved by [fix_URIs.py](https://github.com/uwlib-cams/rml/blob/master/fix_URIs.py).

**Closed by mcm104** 2020-10-19 23:04 UTC
Labels: invalid
